import type { Theme } from './index';
import { hexToHSL } from './utils';

// Define Catppuccin Mocha colors
const catppuccinMochaColors: Record<string, string> = {
  rosewater: '#f5e0dc',
  flamingo: '#f2cdcd',
  pink: '#f5c2e7',
  mauve: '#cba6f7',
  red: '#f38ba8',
  maroon: '#eba0ac',
  peach: '#fab387',
  yellow: '#f9e2af',
  green: '#a6e3a1',
  teal: '#94e2d5',
  sky: '#89dceb',
  sapphire: '#74c7ec',
  blue: '#89b4fa',
  lavender: '#b4befe',
  text: '#cdd6f4',
  subtext1: '#bac2de',
  subtext0: '#a6adc8',
  overlay2: '#9399b2',
  overlay1: '#7f849c',
  overlay0: '#6c7086',
  surface2: '#585b70',
  surface1: '#45475a',
  surface0: '#313244',
  base: '#1e1e2e',
  mantle: '#181825',
  crust: '#11111b',
};

export const catppuccinMocha: Theme = {
  id: 'catppuccin-mocha',
  name: 'Catppuccin Mocha',
  colors: catppuccinMochaColors,
  configPicker: [
    { key: 'red', hex: catppuccinMochaColors.red, label: 'Red' },
    { key: 'mauve', hex: catppuccinMochaColors.mauve, label: 'Mauve' },
    { key: 'blue', hex: catppuccinMochaColors.blue, label: 'Blue' },
    { key: 'green', hex: catppuccinMochaColors.green, label: 'Green' },
    { key: 'peach', hex: catppuccinMochaColors.peach, label: 'Peach' },
    { key: 'pink', hex: catppuccinMochaColors.pink, label: 'Pink' },
  ],
  cssVariables: {
    '--background': hexToHSL(catppuccinMochaColors.base),
    '--foreground': hexToHSL(catppuccinMochaColors.text),
    '--card': hexToHSL(catppuccinMochaColors.mantle),
    '--card-foreground': hexToHSL(catppuccinMochaColors.subtext1),
    '--popover': hexToHSL(catppuccinMochaColors.mantle),
    '--popover-foreground': hexToHSL(catppuccinMochaColors.subtext1),
    '--primary': hexToHSL(catppuccinMochaColors.blue),
    '--primary-foreground': '0 0% 15%',
    '--secondary': hexToHSL(catppuccinMochaColors.surface1),
    '--secondary-foreground': hexToHSL(catppuccinMochaColors.text),
    '--muted': hexToHSL(catppuccinMochaColors.surface1),
    '--muted-foreground': hexToHSL(catppuccinMochaColors.overlay0),
    '--accent': hexToHSL(catppuccinMochaColors.mauve),
    '--accent-foreground': '0 0% 15%',
    '--destructive': hexToHSL(catppuccinMochaColors.red),
    '--destructive-foreground': '0 0% 15%',
    '--border': '234 14% 27%', // #3b3d4f — between surface0 and surface1: visible outlines, not harsh
    '--input': '234 14% 27%',
    '--ring': hexToHSL(catppuccinMochaColors.blue),
    '--sidebar': hexToHSL(catppuccinMochaColors.crust),
    // Catppuccin native colors as CSS variables
    '--rosewater': hexToHSL(catppuccinMochaColors.rosewater),
    '--flamingo': hexToHSL(catppuccinMochaColors.flamingo),
    '--pink': hexToHSL(catppuccinMochaColors.pink),
    '--mauve': hexToHSL(catppuccinMochaColors.mauve),
    '--red': hexToHSL(catppuccinMochaColors.red),
    '--maroon': hexToHSL(catppuccinMochaColors.maroon),
    '--peach': hexToHSL(catppuccinMochaColors.peach),
    '--yellow': hexToHSL(catppuccinMochaColors.yellow),
    '--amber': hexToHSL(catppuccinMochaColors.peach),
    '--green': hexToHSL(catppuccinMochaColors.green),
    '--teal': hexToHSL(catppuccinMochaColors.teal),
    '--sky': hexToHSL(catppuccinMochaColors.sky),
    '--sapphire': hexToHSL(catppuccinMochaColors.sapphire),
    '--blue': hexToHSL(catppuccinMochaColors.blue),
    '--lavender': hexToHSL(catppuccinMochaColors.lavender),
    '--surface': hexToHSL(catppuccinMochaColors.surface1),
    '--surface-0': hexToHSL(catppuccinMochaColors.surface0),
    '--surface-1': hexToHSL(catppuccinMochaColors.surface1),
    '--surface-2': hexToHSL(catppuccinMochaColors.surface2),
    '--overlay': hexToHSL(catppuccinMochaColors.overlay0),
    '--overlay-0': hexToHSL(catppuccinMochaColors.overlay0),
    '--overlay-1': hexToHSL(catppuccinMochaColors.overlay1),
    '--overlay-2': hexToHSL(catppuccinMochaColors.overlay2),
    // Item highlight (dropdown hover/focus)
    '--item-highlight': '0 0% 100%', // white
  },
};
