import type { Theme } from './index';
import { hexToHSL } from './utils';

// Define Rosé Pine Dawn colors (15 official colors)
const rosepineDawnColors: Record<string, string> = {
  base: '#faf4ed',
  surface: '#fffaf3',
  overlay: '#f2e9e1',
  muted: '#9893a5',
  subtle: '#797593',
  text: '#464261',
  love: '#b4637a',
  gold: '#ea9d34',
  rose: '#d7827e',
  pine: '#286983',
  foam: '#56949f',
  iris: '#907aa9',
  'highlight-low': '#f4ede8',
  'highlight-med': '#dfdad9',
  'highlight-high': '#cecacd',
};

export const rosepineDawn: Theme = {
  id: 'rosepine-dawn',
  name: 'Rosé Pine Dawn',
  colors: rosepineDawnColors,
  configPicker: [
    { key: 'love', hex: rosepineDawnColors.love, label: 'Love' },
    { key: 'iris', hex: rosepineDawnColors.iris, label: 'Iris' },
    { key: 'pine', hex: rosepineDawnColors.pine, label: 'Pine' },
    { key: 'foam', hex: rosepineDawnColors.foam, label: 'Foam' },
    { key: 'gold', hex: rosepineDawnColors.gold, label: 'Gold' },
    { key: 'rose', hex: rosepineDawnColors.rose, label: 'Rose' },
  ],
  cssVariables: {
    // Semantic mappings
    '--background': hexToHSL(rosepineDawnColors.base),
    '--foreground': hexToHSL(rosepineDawnColors.text),
    '--card': hexToHSL(rosepineDawnColors.surface),
    '--card-foreground': hexToHSL(rosepineDawnColors.subtle),
    '--popover': hexToHSL(rosepineDawnColors.surface),
    '--popover-foreground': hexToHSL(rosepineDawnColors.subtle),
    '--primary': hexToHSL(rosepineDawnColors.pine),
    '--primary-foreground': hexToHSL(rosepineDawnColors.surface),
    '--secondary': hexToHSL(rosepineDawnColors.overlay),
    '--secondary-foreground': hexToHSL(rosepineDawnColors.text),
    '--muted': hexToHSL(rosepineDawnColors.overlay),
    '--muted-foreground': hexToHSL(rosepineDawnColors.muted),
    '--accent': hexToHSL(rosepineDawnColors.iris),
    '--accent-foreground': hexToHSL(rosepineDawnColors.surface),
    '--destructive': hexToHSL(rosepineDawnColors.love),
    '--destructive-foreground': hexToHSL(rosepineDawnColors.surface),
    '--border': '258 15% 71%', // #b5aec1 — darker than highlight-high: visible separation on light bg
    '--input': '258 15% 71%',
    '--ring': hexToHSL(rosepineDawnColors.pine),
    '--sidebar': hexToHSL(rosepineDawnColors['highlight-med']),
    // Popover/dropdown background alpha (light: translucent text-on-text is unreadable)
    '--popover-alpha': '1',
    // Rosé Pine Dawn native colors as CSS variables
    '--love': hexToHSL(rosepineDawnColors.love),
    '--gold': hexToHSL(rosepineDawnColors.gold),
    '--amber': hexToHSL(rosepineDawnColors.gold),
    '--yellow': hexToHSL(rosepineDawnColors.gold),
    '--rose': hexToHSL(rosepineDawnColors.rose),
    '--pine': hexToHSL(rosepineDawnColors.pine),
    '--foam': hexToHSL(rosepineDawnColors.foam),
    '--iris': hexToHSL(rosepineDawnColors.iris),
    '--highlight-low': hexToHSL(rosepineDawnColors['highlight-low']),
    '--highlight-med': hexToHSL(rosepineDawnColors['highlight-med']),
    '--highlight-high': hexToHSL(rosepineDawnColors['highlight-high']),
    '--base': hexToHSL(rosepineDawnColors.base),
    '--surface': hexToHSL(rosepineDawnColors.surface),
    '--overlay': hexToHSL(rosepineDawnColors.overlay),
    '--muted-color': hexToHSL(rosepineDawnColors.muted),
    '--subtle': hexToHSL(rosepineDawnColors.subtle),
    // Catppuccin-compatible variables (mapped to Rosé Pine equivalents)
    '--rosewater': hexToHSL(rosepineDawnColors.subtle),
    '--flamingo': hexToHSL(rosepineDawnColors.rose),
    '--pink': hexToHSL(rosepineDawnColors.love),
    '--mauve': hexToHSL(rosepineDawnColors.iris),
    '--red': hexToHSL(rosepineDawnColors.love),
    '--maroon': hexToHSL(rosepineDawnColors.love),
    '--peach': hexToHSL(rosepineDawnColors.gold),
    '--green': hexToHSL(rosepineDawnColors.foam),
    '--teal': hexToHSL(rosepineDawnColors.foam),
    '--sky': hexToHSL(rosepineDawnColors.foam),
    '--sapphire': hexToHSL(rosepineDawnColors.pine),
    '--blue': hexToHSL(rosepineDawnColors.pine),
    '--lavender': hexToHSL(rosepineDawnColors.iris),
    '--surface-0': hexToHSL(rosepineDawnColors['highlight-low']),
    '--surface-1': hexToHSL(rosepineDawnColors.overlay),
    '--surface-2': hexToHSL(rosepineDawnColors['highlight-high']),
    '--overlay-0': hexToHSL(rosepineDawnColors.muted),
    '--overlay-1': hexToHSL(rosepineDawnColors.subtle),
    '--overlay-2': hexToHSL(rosepineDawnColors.text),
    // Item highlight (dropdown hover/focus)
    '--item-highlight': '0 0% 0%', // black
  },
};
